<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\MSBuild.Dag.MSBuild\MSBuild.Dag.MSBuild.csproj" />
    <ProjectReference Include="..\MSBuild.Dag.Visualization\MSBuild.Dag.Visualization.csproj" />
    <ProjectReference Include="..\MSBuild.Dag.Execution\MSBuild.Dag.Execution.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Build.Locator" Version="1.11.2" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
